---
- hosts: compute
  vars_files:
    - vars/quobyte.yaml
  become: yes
  tasks:

    - name: Stop client
      service:
        name: quobyte-client
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove client package
      yum:
        name: quobyte-client 
        state: absent
        update_cache: yes

    - name: Remove client config file
      file:
        path: /etc/quobyte/client-service.cfg
        state: absent

    - name: Remove mount point
      file:
        path: /quobyte
        state: absent
