#
# Repository Id for OracleCloud
repo_id: FTSUx9VMUtNUTQJB7AGf0cjaDhrT27HH

# Client network
client_network: 10.0.6.0/24

#Service network
service_network: 10.0.3.0/24

#
# Mount point for the Quobyte client
mountpoint: /quobyte
